development:
  adapter: postgresql 
  encoding: unicode
  database: shuttin_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql 
  encoding: unicode
  database: shuttin_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql 
  encoding: unicode
  database: shuttin_production
  pool: 5
  username:
  password:

